--CREATE DATABASE ProyectoDiciembre

CREATE TABLE TiposDocumento (
	Id INT IDENTITY(1, 101) PRIMARY KEY,
	Title VARCHAR(4) NOT NULL
)

CREATE TABLE Personas (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Apellido	 VARCHAR(50) NOT NULL,
	NumeroIdentificacion VARCHAR(10) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	FechaCreacion DATETIME DEFAULT GETDATE(),
	TipoDocumentoId INT NOT NULL,

	FOREIGN KEY (TipoDocumento) REFERENCES TipoIdentificacion(Id)
)

CREATE TABLE Usuarios (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Usuario INT NOT NULL,
	Pass VARCHAR(150) NOT NULL,
	FechaCreacion DATETIME DEFAULT GETDATE()
)